apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: demo-alpine
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine-1
  name: alpine-1
spec:
  containers:
  - image: docker.io/library/alpine
    name: alpine-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
