apiVersion: v1
kind: Service
metadata:
  name: apachewww
  labels: 
    app: apachewww
spec:
  selector:
    app: apachewww
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP
