FROM docker.io/jamesbrink/php:latest
#FROM php:8.2-fpm-alpine

LABEL description="Built for training purposes using ubi-v10 and php-v8.3 from redhat container catalog. Source /opt/app-root/src/ has some simple php code to retrieve client&server IPs as well as port information. Uses 8080"

RUN sed -i "s/80/8080/" /etc/apache2/httpd.conf

#WORKDIR /var/www/html/
WORKDIR /var/www/localhost/htdocs

RUN mkdir -p /var/www/localhost/htdocs /var/log/apache2 /var/run/apache2 /var/lock/apache2 \
    && chown -R 1001:0 /var/www/localhost/htdocs /var/log/apache2 /var/run/apache2 /var/lock/apache2 \
    && chmod -R g+rwx /var/www/localhost/htdocs /var/log/apache2 /var/run/apache2 /var/lock/apache2 

COPY --chown=1000:0 docs/* ./

EXPOSE 8080

USER 1001

CMD ["apache2-foreground"]
