apiVersion: apps/v1
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: demo-nginx
spec: {}
status: {}
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxwww
    color: red
  name: nginxwww
  namespace: demo-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxwww
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxwww
    spec:
      serviceAccountName: mysa1
      containers:
      - image: registry.access.redhat.com/hi/httpd:latest
        name: webserver
---  
apiVersion: v1
kind: Service
metadata:
  name: nginxwww
  labels: 
    app: nginxwww
  namespace: demo-nginx
spec:
  selector:
    app: nginxwww
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---    
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa1
  namespace: demo-nginx
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: mysa1
  namespace: default
---    
