apiVersion: v1
kind: Service
metadata:
  name: nginxwww
  labels: 
    app: nginxwww
spec:
  selector:
    app: nginxwww
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP
